Added support for different input types, added tests.
phyloref/phylo2owl pull request #15
Opened 2016-12-06 23:09 UTC by gaurav

Added support for a '-t' command line argument to phylo2owl, which takes one of three input types ('newick', 'nexus', 'nexml'); added tests to make sure each of these results the same OWL output as each other. Closes #11.

2016-12-07 17:29 UTC, hlapp requested changes
Looks good overall; can you check and respond to the two comments I left?

2016-12-07 17:29 UTC, hlapp commented on phylo2owl.py
> +    '-t', '--type', dest='input_type', nargs='?',
I'm wondering whether we shouldn't better name this `-f` and `--format`, respectively; my feeling is that's much more common and thus more easily remembered?

2016-12-07 17:29 UTC, hlapp commented on phylo2owl.py
> -import inspect
Is this change part of adding support for multiple input formats?

2016-12-12 23:53 UTC, gaurav commented on phylo2owl.py
> -import inspect
Oops, sorry about that! Moved into its own commit, @22b147a -- or should I remove this from this pull request entirely?

2016-12-12 23:55 UTC, gaurav commented on phylo2owl.py
> +    '-t', '--type', dest='input_type', nargs='?',
Yes, it's much clearer! Fixed in @0bd1db3.

2016-12-13 16:49 UTC, hlapp commented on phylo2owl.py
> -import inspect
Yes, let's try to keep pull requests focused.

2016-12-13 16:51 UTC, hlapp commented on README.md
> +phylo2owl [input.(tre|phy|xml|...)] [-f format] [-o output.owl]
Shouldn't this mention the `--format` alternative as well?

2016-12-15 06:39 UTC, gaurav commented on phylo2owl.py
> -import inspect
Done! I've moved it to a "code_cleanup" branch and deleted it from here; once there's enough fixes there, I'll turn that into its own pull request.

2016-12-15 06:41 UTC, gaurav commented on README.md
> +phylo2owl [input.(tre|phy|xml|...)] [-f format] [-o output.owl]
I think of the README file as a synopsis that tells you just enough to get you started; running `python phylo2owl.py --help` displays the full list of options, including short and long forms for each option.

2017-01-04 23:38 UTC, gaurav commented on README.md
> +phylo2owl [input.(tre|phy|xml|...)] [-f format] [-o output.owl]
I've expanded the command line options section at https://github.com/gaurav/phylo2owl/tree/support_for_nexml_and_nexus#command-line-options -- will that do?

2017-01-06 18:59 UTC, hlapp approved these changes

2017-01-06 19:00 UTC, hlapp commented
I'll leave the choice of merge method to you, @gaurav, but go ahead and merge.

2017-01-06 22:49 UTC, merged